image: node:alpine
definitions:
  caches:
   yarn: ~/.yarn
pipelines:
  default:
    - step:
        name: Validate code
        caches:
          - yarn
        script:
          - yarn install
          - cd ios && pod install
          - cd android && ./gradlew clean
          