export default {
  Background: require('../assets/images/BG.png'),
  Background2x: require('../assets/images/BG2x.png'),
  Background3x: require('../assets/images/BG3x.png'),

  // Transactions and instant trades
  Arrow: require('../assets/images/Arrow.png'),
  Left: require('../assets/images/Left.png'),
  Right: require('../assets/images/Right.png'),
  Calendar: require('../assets/images/Calendar.png'),
  Clear: require('../assets/images/Clear.png'),
  Close: require('../assets/images/Close.png'),
  Copy: require('../assets/images/Copy.png'),
  Deposit: require('../assets/images/Deposit.png'),
  Download: require('../assets/images/Download.png'),
  Exchange_Active: require('../assets/images/Exchange_Active.png'),
  Exchange: require('../assets/images/Exchange.png'),
  Failed: require('../assets/images/Failed.png'),
  Filter: require('../assets/images/Filter.png'),
  Focused: require('../assets/images/Focused.png'),
  Logo: require('../assets/images/Logo.png'),
  Pending: require('../assets/images/Pending.png'),
  Search: require('../assets/images/Search.png'),
  Success: require('../assets/images/Success.png'),
  Trade_Active: require('../assets/images/Trade_Active.png'),
  Trade: require('../assets/images/Trade.png'),
  Transactions_Active: require('../assets/images/Transactions_Active.png'),
  Transactions: require('../assets/images/Transactions.png'),
  Wallet_Tab_Active: require('../assets/images/Wallet_Active.png'),
  Wallet_Tab: require('../assets/images/Wallet.png'),
  Withdrawal: require('../assets/images/Withdrawal.png'),
  AMEX: require('../assets/images/Amex.png'),
  MASTERCARD: require('../assets/images/MC_Card.png'),
  VISA: require('../assets/images/Visa.png'),
  TBC: require('../assets/images/TBC.png'),

  //User Profile
  Back: require('../assets/images/User_profile/Back.png'),
  Identity: require('../assets/images/User_profile/Identity.png'),
  Phone: require('../assets/images/User_profile/Phone.png'),
  Notifications: require('../assets/images/User_profile/Notifications.png'),
  Language: require('../assets/images/User_profile/Language.png'),
  Biometric: require('../assets/images/User_profile/Biometric.png'),
  E_Mail_Verified: require('../assets/images/User_profile/E_Mail_Verified.png'),
  E_Mail_Not_Verified: require('../assets/images/User_profile/E_Mail_Not_Verified.png'),
  E_mail_Auth: require('../assets/images/User_profile/E_mail_Auth.png'),
  Google_Auth: require('../assets/images/User_profile/Google_Auth.png'),
  SMS_Auth: require('../assets/images/User_profile/SMS_Auth.png'),
  Pin: require('../assets/images/User_profile/Pin.png'),
  Strong_Password: require('../assets/images/User_profile/Strong_Password.png'),
  Hide: require('../assets/images/User_profile/Hide.png'),
  Show: require('../assets/images/User_profile/Show.png'),
  Appstore: require('../assets/images/User_profile/Appstore.png'),
  Playstore: require('../assets/images/User_profile/Playstore.png'),
  User: require('../assets/images/User_profile/User.png'),
  Portfolio: require('../assets/images/User_profile/Portfolio.png'),

  // Wallet
  Wallet: require('../assets/images/Wallet/Wallet.png'),
  Warning: require('../assets/images/Wallet/Warning.png'),
  Warning_White: require('../assets/images/Wallet/Warning_White.png'),
  QR: require('../assets/images/Wallet/QR.png'),
  Binance: require('../assets/images/Wallet/Binance.png'),
  Menu: require('../assets/images/Wallet/Menu.png'),
  Edit: require('../assets/images/Wallet/Edit.png'),
  Delete_White: require('../assets/images/Wallet/Delete_White.png'),
  Delete: require('../assets/images/Wallet/Delete.png'),
  White_Copy: require('../assets/images/Wallet/White_Copy.png'),
  List: require('../assets/images/Wallet/List.png'),
  Card: require('../assets/images/Wallet/Card.png'),
  Address_List: require('../assets/images/Wallet/Address_List.png'),
  Swift: require('../assets/images/Wallet/Swift.png'),
  Time: require('../assets/images/Wallet/Time.png'),
  Generate: require('../assets/images/Wallet/Generate.png'),
  Add: require('../assets/images/Wallet/Add.png'),
  Check_Full: require('../assets/images/Wallet/Check_Full.png'),
  Check_Empty: require('../assets/images/Wallet/Check_Empty.png'),

  // CURRENCIES
  BTC: require('../assets/images/Currencies/BTC.png'),
  USD: require('../assets/images/Currencies/USD.png'),
  ETH: require('../assets/images/Currencies/ETH.png'),

  // FLAGS
  GEO: require('../assets/images/Flags/GEO.png'),
};
