export default {
  Arrow: require('../assets/images/Arrow.png'),
  Left: require('../assets/images/Left.png'),
  Right: require('../assets/images/Right.png'),
  Calendar: require('../assets/images/Calendar.png'),
  Clear: require('../assets/images/Clear.png'),
  Close: require('../assets/images/Close.png'),
  Copy: require('../assets/images/Copy.png'),
  Deposit: require('../assets/images/Deposit.png'),
  Download: require('../assets/images/Download.png'),
  Exchange_Active: require('../assets/images/Exchange_Active.png'),
  Exchange: require('../assets/images/Exchange.png'),
  Failed: require('../assets/images/Failed.png'),
  Filter: require('../assets/images/Filter.png'),
  Focused: require('../assets/images/Focused.png'),
  Logo: require('../assets/images/Logo.png'),
  Pending: require('../assets/images/Pending.png'),
  Search: require('../assets/images/Search.png'),
  Success: require('../assets/images/Success.png'),
  Trade_Active: require('../assets/images/Trade_Active.png'),
  Trade: require('../assets/images/Trade.png'),
  Transactions_Active: require('../assets/images/Transactions_Active.png'),
  Transactions: require('../assets/images/Transactions.png'),
  Wallet_Active: require('../assets/images/Wallet_Active.png'),
  Wallet: require('../assets/images/Wallet.png'),
  Withdrawal: require('../assets/images/Withdrawal.png'),
  AMEX: require('../assets/images/Amex.png'),
  MASTERCARD: require('../assets/images/MC_Card.png'),
  VISA: require('../assets/images/Visa.png'),
  TBC: require('../assets/images/TBC.png'),

  // CURRENCIES
  BTC: require('../assets/images/Currencies/BTC.png'),
  USD: require('../assets/images/Currencies/USD.png'),
  ETH: require('../assets/images/Currencies/ETH.png'),
};
