export const enum Execution {
	LOGIN_USERNAME_PASSWORD = 'LOGIN_USERNAME_PASSWORD',
	EMAIL_VERIFICATION_OTP = 'EMAIL_VERIFICATION_OTP',
	REGISTRATION_START = 'REGISTRATION_START',
	LOGIN_OTP = 'LOGIN_OTP',
	OTP_RESET_INSTRUCTIONS = 'OTP_RESET_INSTRUCTIONS',
}
